const productsData = [
    {
      id: 1,
      title: 'Product 1',
      description: 'Description for Product 1',
      price: 49.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
      category: 'electronics',
    },
    {
      id: 2,
      title: 'Product 2',
      description: 'Description for Product 2',
      price: 19.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
      category: 'clothing',
    },
    {
      id: 3,
      title: 'Product 3',
      description: 'Description for Product 3',
      price: 29.99,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
      category: 'books',
    },
    {
        id: 4,
        title: 'Product 1',
        description: 'Description for Product 1',
        price: 49.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'electronics',
      },
      {
        id: 5,
        title: 'Product 2',
        description: 'Description for Product 2',
        price: 19.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'clothing',
      },
      {
        id: 6,
        title: 'Product 3',
        description: 'Description for Product 3',
        price: 29.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'books',
      },
      {
        id: 7,
        title: 'Product 1',
        description: 'Description for Product 1',
        price: 49.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'electronics',
      },
      {
        id: 8,
        title: 'Product 2',
        description: 'Description for Product 2',
        price: 19.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'clothing',
      },
      {
        id: 9,
        title: 'Product 3',
        description: 'Description for Product 3',
        price: 29.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'books',
      },
      {
        id: 10,
        title: 'Product 1',
        description: 'Description for Product 1',
        price: 49.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'electronics',
      },
      {
        id: 11,
        title: 'Product 2',
        description: 'Description for Product 2',
        price: 19.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'clothing',
      },
      {
        id: 12,
        title: 'Product 3',
        description: 'Description for Product 3',
        price: 29.99,
        image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXaNPGxBAMRMDmfPqY9aYHJqp0K1ar3NlOb4gehO4B&s',
        category: 'books',
      },
  ];
  
  export default productsData;
  